version: '3'
services:
  frontend:
    build: ./frontend
    ports:
      - '3000:3000'
    volumes:
      - ./frontend:/app
      - /app/node_modules/
    environment:
      - WATCHPACK_POLLING=true
  api:
    build: ./api
    ports:
      - '5050:5050'
    volumes:
      - ./api:/app
      - /app/.venev/
  mongo:
    image: mongo:7.0.4
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: Admin
      MONGO_INITDB_ROOT_PASSWORD: Admin
    volumes:
      - mongodb_data:/data/db
  mongo-express:
    image: mongo-express:1.0.0-18
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://Admin:Admin@mongo:27017/
      ME_CONFIG_MONGODB_ADMINUSERNAME: Admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: Admin
      ME_CONFIG_BASICAUTH: false
      ME_CONFIG_BASICAUTH_USERNAME: ''
    depends_on:
      - mongo

volumes:
  mongodb_data: