version: '3'
services:
  frontend:
    build: ./frontend
    ports:
      - '3000:3000'
    volumes:
      - ./frontend:/app
      - /app/node_modules/
    environment:
      - WATCHPACK_POLLING=true
  api:
    build: ./api
    ports:
      - '5050:5050'
    volumes:
      - ./api:/app
      - /app/.venev/